### ISSUE TITLE
第八天

### ISSUE THREAD

**Issue by lianjianbo** [lianjianbo/kobe#9]
# 学习计划第八天
[Class与Style绑定](##Class与Style绑定)
[demo](##demo)
[参考文章](##参考文章)
## Class 与 Style 绑定
* 绑定对象 
通过v-bind绑定一个class对象，这样就可以动态的去改变class。
例如
```html
<div v-bind:class="{ active: isActive }"></div>
```
```css
.active{background-color:#FF0000} //背景颜色为红色
```
在data里返回isActive：true,（如果为false，则不能改变css中的样式）那么css中就可以.active{}修改div的样式了。
当然v-bind:class 指令可以与普通的 class 属性共存
例如
```html
<div class="static" v-bind:class="{ active: isActive }"></div>
```
data里是
```js
{
isActive: true,
}
```
```css
.static{width: 100px;height: 100px;border: 5px solid #0000FF}
	.active{background-color:#FF0000}
```
以上将会展示出有着蓝色并且有5像素的边框，100像素的宽和高和背景颜色为红色的一个方框
也就是上述代码就会相当于
```html
<div>class="static active"</div>
```
也就是，当static或者是active发生变化时，页面都会重新渲染。(亲测，确实是这样的)
* 绑定内联样式
也可以绑定内联样式比如
```html
<div v-bind:style="{ color: activeColor, fontSize: fontSize + 'px' }"></div>
```
data里这么写

```js{
  activeColor: 'blue',
  fontSize: 30
}
```
也可以这样写，比较直观
<div v-bind:style="demo"></div>
在data里这么写
  demo: {
    color: 'red',
    fontSize: '13px'
  }

## demo
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title></title>
<script src="vue.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>
<div id="app">
	<div  v-bind:class="{ result: resultIs}">
		hello
	</div>
	
</div>
```
```js
<script type="text/javascript">
var vm = new Vue({
	el : "#app",
	data : {
		resultIs : true,
	}
});
</script>
```
```css
<style>
.result{
background:#77FFEE; 
width:100px; 
height:100px; 
display: flex; 
align-items: center;
justify-content: center;f
lex-direction:column;
}
</style>
```
```html
</body>
</html>

```
## 参考文章
[Class与Style绑定](https://cn.vuejs.org/v2/guide/class-and-style.html)
